title: 'Going Places'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Totam sed quis ut eos omnis. Cupiditate molestiae quisquam reprehenderit. Mollitia velit hic alias tenetur ipsam ea sit officiis perspiciatis illum sit eveniet labore. Ea autem totam animi magni officia deleniti quisquam illo et ex iusto sed.'
updated_by: 29
updated_at: 1691709968
blueprint: item
